package cli

import "testing"

func TestBuildAgentPromptWithContext(t *testing.T) {
	got := buildAgentPrompt("on-branch-main", true, "Summarize the repo.\n")
	want := "## Project context (generated by Runefile [context] task)\n" +
		"on-branch-main\n\n## Task\nSummarize the repo.\n"
	if got != want {
		t.Errorf("prompt =\n%q\nwant\n%q", got, want)
	}
}

func TestBuildAgentPromptWithoutContext(t *testing.T) {
	if got := buildAgentPrompt("", false, "Summarize.\n"); got != "Summarize.\n" {
		t.Errorf("no hook: prompt must pass through unchanged, got %q", got)
	}
}
