package cli

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/rune-task-runner/rune/internal/ast"
	"github.com/rune-task-runner/rune/internal/runtime/agent"
	"github.com/rune-task-runner/rune/internal/runtime/shell"
	"github.com/rune-task-runner/rune/mcpserver"
)

// executeAgent runs an (agent) task: it interpolates the prompt body, starts an
// in-process MCP endpoint exposing the project's non-destructive tasks for the
// agent to call back into, drives the configured agent CLI, and writes the
// agent's final output to stdout.
func (e *engine) executeAgent(task *ast.Task, lines []shell.Line, dir string, env []string) error {
	var body strings.Builder
	for _, ln := range lines {
		body.WriteString(ln.Text)
		body.WriteByte('\n')
	}

	opts := agent.Options{
		AgentCmd: e.settings.AgentCmd,
		Dir:      dir,
		Env:      env,
		Stdin:    e.opts.Stdin,
		Stderr:   e.opts.Stderr,
	}

	// Best-effort: gather fresh [context] hook output for this invocation
	// (spec 021 FR-003) and expose allowed (non-destructive, non-private)
	// tasks to the agent over a localhost, token-gated MCP endpoint. The
	// same adapter serves both; its Tasks() already excludes the hook.
	var contextText string
	if e.file != nil {
		if adapter := e.newAgentAdapter(); adapter != nil {
			contextText = adapter.gatherContext(e.ctx, e.opts.Stderr)

			token := randomToken()
			srv := mcpserver.New(adapter, mcpserver.Options{AllowDestructive: false, Version: e.opts.Version})
			if addr, stop, err := srv.StartHTTP(mcpserver.HTTPConfig{Addr: "127.0.0.1:0", Token: token}); err == nil {
				defer stop()
				opts.MCPURL = "http://" + addr
				opts.MCPToken = token
			} else {
				// Still best-effort, but say so: a silent skip leaves the
				// user wondering why the agent has no tool access.
				fmt.Fprintf(e.opts.Stderr, "%s: agent MCP endpoint unavailable; the agent runs without task tools: %v\n",
					e.theme.Warning.Render("warning"), err)
			}
		}
	}

	finalText, err := agent.CLIProvider{}.Run(e.ctx, buildAgentPrompt(contextText, body.String()), opts)
	if err != nil {
		return err
	}
	if finalText != "" {
		fmt.Fprint(e.opts.Stdout, finalText)
		if !strings.HasSuffix(finalText, "\n") {
			fmt.Fprintln(e.opts.Stdout)
		}
	}
	return nil
}

// newAgentAdapter builds an MCP engine adapter from the engine's module state.
// It derives the same secret-value mask set as the `rune serve` path so a task
// the agent calls back into cannot leak a credential verbatim into the agent's
// chat history (the write-back surface the feature exists to protect).
func (e *engine) newAgentAdapter() *mcpAdapter {
	return &mcpAdapter{
		file:      e.file,
		tasks:     e.tasks,
		assigns:   e.assigns,
		settings:  e.settings,
		root:      e.root,
		workDir:   e.workDir,
		baseEnv:   e.env,
		overrides: e.overrides,
		maskSet:   deriveMaskSet(e.env, e.tasks, e.settings.Secrets, e.settings.Unmasked),
		now:       e.now,
		goos:      e.goos,
	}
}

// buildAgentPrompt assembles the provider prompt: when the [context] hook
// produced text it is prepended under fixed delimiters (spec 021 FR-003);
// with no context text — no hook, an OS-skipped hook, or a hook that printed
// nothing — the body passes through unchanged, never a bare header (FR-009).
func buildAgentPrompt(contextText, body string) string {
	if contextText == "" {
		return body
	}
	return "## Project context (generated by Runefile [context] task)\n" +
		contextText + "\n\n## Task\n" + body
}

func randomToken() string {
	var b [16]byte
	_, _ = rand.Read(b[:])
	return hex.EncodeToString(b[:])
}
