package integration

import (
	"strings"
	"testing"
)

// The stub agent is sh printing its $1 — exactly the prompt CLIProvider
// appends as the last argument — so the task's stdout IS the assembled
// prompt (spec 021 US2).
const contextRunefile = `set agent_cmd := ["sh", "-c", "printf '%s' \"$1\"", "rune-agent-stub"]

# Gather project health for agents.
[context]
health:
    @echo ctx-marker-branch-main

# Summarize recent work.
triage (agent):
    Summarize the last commits.
`

func TestContextPrefixReachesAgentPrompt(t *testing.T) {
	dir := writeRunefile(t, contextRunefile)
	r := run(t, dir, nil, "triage")
	if r.code != 0 {
		t.Fatalf("exit = %d; stderr=%s", r.code, r.stderr)
	}
	for _, want := range []string{
		"## Project context (generated by Runefile [context] task)",
		"ctx-marker-branch-main",
		"## Task",
		"Summarize the last commits.",
	} {
		if !strings.Contains(r.stdout, want) {
			t.Errorf("prompt missing %q; stdout=%q", want, r.stdout)
		}
	}
}

// The [context] hook stays a normal CLI task, runnable by name (FR-006).
func TestContextTaskRemainsCLIInvocable(t *testing.T) {
	dir := writeRunefile(t, contextRunefile)
	r := run(t, dir, nil, "health")
	if r.code != 0 {
		t.Fatalf("exit = %d; stderr=%s", r.code, r.stderr)
	}
	if !strings.Contains(r.stdout, "ctx-marker-branch-main") {
		t.Errorf("hook output missing from direct run; stdout=%q", r.stdout)
	}
}

// A failing hook must never block the agent task (spec 021 US3, FR-005).
func TestContextHookFailureStillRunsAgent(t *testing.T) {
	failing := strings.Replace(contextRunefile, "@echo ctx-marker-branch-main", "@exit 3", 1)
	dir := writeRunefile(t, failing)
	r := run(t, dir, nil, "triage")
	if r.code != 0 {
		t.Fatalf("agent task must survive a failing hook: exit=%d stderr=%s", r.code, r.stderr)
	}
	if !strings.Contains(r.stdout, "failed; proceeding without project context") {
		t.Errorf("degrade notice should appear in the prompt; stdout=%q", r.stdout)
	}
	if !strings.Contains(r.stderr, "context hook") {
		t.Errorf("warning should reach rune's stderr; stderr=%q", r.stderr)
	}
}
